name: CI


on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploiement dans Azure
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login Az Cli
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script Creation d'un "Resource Group"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.9.0
        inlineScript: |
          az group create --name RG-GitHub-Demo --location eastus2
