name: CI


on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploiement dans Azure
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login Az Cli
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script Creation d'un "Resource Group"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.9.0
        inlineScript: |
          az group create --name ${{ secrets.AZURE_RG }} --location ${{ secrets.AZURE_LOCATION }}

    - name: Git - Recupération des sources
      uses: actions/checkout@master

    - name: Azure - Login ARM
      uses: Azure/github-actions/login@master
      env:
        AZURE_SUBSCRIPTION: "Peter_Azure"
        AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
        AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
        AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}

    - name: Azure - Deploy ARM Template
      uses: Azure/github-actions/arm@master
      env:
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RG }}
        AZURE_TEMPLATE_LOCATION: ./ARM/azuredeploy.json
        AZURE_TEMPLATE_PARAM_LOCATION: ./ARM/azuredeploy.parameters.json
        